### ISSUE TITLE
Attribute `run` missing after niv update 

### ISSUE THREAD

**Issue by avdv** [cachix/pre-commit-hooks.nix#104]
Hi.

After running a `niv update` I get this error when entering nix-shell:
```
unpacking 'https://github.com/cachix/pre-commit-hooks.nix/archive/6363c4e3950ba528e0fbccdb7df5d43e09170d8d.tar.gz'...
copying path '/nix/store/rkpyq2gjzmavfrrsq68w1jxg4cx0gd02-source' from 'https://pre-commit-hooks.cachix.org'...
error: attribute 'run' missing, at nix/default.nix:27:24
```
line 27 is this (courtesy of the getting-started-nix-template ;-)):
```
    pre-commit-check = (import sources."pre-commit-hooks.nix").run {
```
Maybe the flakes support broke this?

Reverting back to caba2a7208abd6a2dae2c8afd8e2a818108b1376 made it work again.

**Comment by domenkozar** [comment]
Thanks, should be fixed in master.
