### ISSUE TITLE
Support specifying stages for individual hooks

### ISSUE THREAD

**Issue by sd234678** [cachix/pre-commit-hooks.nix#110]
Continuation of #49 

Currently, it's possible to specify `default_stages` for all hooks, which also configures which stages hooks are installed for.

Via the `raw` attribute on an individual hook, it's possible to specify `stages` for a single hook, though if any stage specified is not in the `default_stages`, the hook will not be installed.

So I suppose there are two aspects to this:

1. Add a `stages` config property on the hook level
2. Update `install_stages` to install both default stages (per current behaviour) and any specified in individual hooks

I'm happy to work on the implementation for this but it might be a few days before I get the time to do so, so I figured I'd post here first in case anyone has any comments.

**Comment by roberth** [comment]
Sounds good to me. Can probably be implemented without problems or upstream change, but just in case:

The upstream pre-commit maintainer regards our wrapper as a niche use case, and he gets many requests. If this feature needs a change in pre-commit behavior, please make sure it's useful to his wider audience and be respectful of his free time.
