### ISSUE TITLE
`pre-commit` not found.  Did you forget to activate your virtualenv?

### ISSUE THREAD

**Issue by DavHau** [cachix/pre-commit-hooks.nix#140]
The generated hooks seem to depend on the shellHook being excecuted.
If I try to create a commit from within vscode, it errors out with:
```
`pre-commit` not found.  Did you forget to activate your virtualenv?
```

It would probably be good if `.git/hooks/pre-commit` would be wrapped in order not to depend on the environment being set up.

Any other possible solutions to this problem?

**Comment by roberth** [comment]
`pre-commit` installs that file by itself, so implementing your suggestion requires a patch to the pre-commit sources.
The patch could live in
 - pre-commit upstream, but I think this is too Nix-specific
 - as a patch in Nixpkgs
 - here, although here it can go out of sync. That's easier to solve in Nixpkgs



> Any other possible solutions to this problem?

Do you run the Nix Environment Selector plugin?
I don't commit with vscode, but I do use that plugin to provide dependencies of some other plugins, such as language servers.

**Comment by DavHau** [comment]
The vscode extension `Nix Environment Selector` seems to work.
Thanks
