### ISSUE TITLE
Upgrade Haskell formatters (fourmolu/ormoulu)

### ISSUE THREAD

**Issue by bladyjoker** [cachix/pre-commit-hooks.nix#155]
Hi,

First of all, thanks a ton for delivering such a useful project, you've made so many lives easier!

Secondly, I'm having some trouble with Haskell formatters, specifically `fourmolu`, as atm it's a pretty old version of the tool that's being used and the `settings.ormolu.defaultExtensions` setting is cumbersome to manage as it requires one to manage the extension set in both Cabal and pre-commit-hooks.nix configuration.

The latest version of `ormolu` don't support the `--cabal-default-extensions` flag as well as `fourmolu`:
- https://github.com/fourmolu/fourmolu/commit/6939a9b8de0b41da6e6a0cd8341fa6acdadf4d83
- https://github.com/tweag/ormolu/commit/4b5ba705d7bb1b433339fa7c35ad089b68677c2f

and it seems like that's the default behavior now to scan the Cabal file for `default-extensions` stanza. How would you feel about upgrading these packages?

**Comment by domenkozar** [comment]
Done: https://github.com/cachix/pre-commit-hooks.nix/pull/158
