### ISSUE TITLE
how to disable pre-commit-hook in nix flake check only?

### ISSUE THREAD

**Issue by hlolli** [cachix/pre-commit-hooks.nix#163]
I have a pre-commit hook for running tsc typecheck on each changed file with https://www.npmjs.com/package/tsc-files this is super useful for developers. But we are having an issue including this hook, because our ci runs nix flake check, and this hook will fail, because it's impure. Typescript needs specific packages from our monorepo built and symlinked. I'd be happy with just disabling it on nix flake check only, but run this hook always otherwise. I just don't see a good way to achieve this. It would need to be some sort of conditional enable, with args perhaps?

**Comment by roberth** [comment]
If you use flake.parts, you can set `pre-commit.check.enable = false;` in `perSystem`.
Otherwise, put the check (`run`) in a let binding instead of in the `checks` attribute.

**Comment by hlolli** [comment]
yes absolutely correct, since I had forgotten how the shellHook was applied. So basically I want a different shellHook from checks. Easy.

now I have

```nix
let
    defined-pre-commit-hooks = import ./nix/pre-commit-hooks.nix { inherit pkgs; };
     pre-commit-check-hook = pre-commit-hooks.lib.${system}.run {
          src = ./.;
          hooks = {
            inherit (defined-pre-commit-hooks) check-i-want-sometimes check-i-always-want;
          };
        };
# in flake body..
        checks = {
          pre-commit-check = pre-commit-hooks.lib.${system}.run {
            src = ./.;
            hooks = {
              inherit (defined-pre-commit-hooks) check-i-always-want;
            };
          };
# in devShell
shellHook = ''
            ${pre-commit-check-hook.shellHook}
            '';
```

something like that, thanks for your help :) !
