### ISSUE TITLE
cabal2nix hook

### ISSUE THREAD

**Issue by NorfairKing** [cachix/pre-commit-hooks.nix#168]
To prevent having to use IFD using `callCabal2nix`, it would be nice if there was a hook that would run `cabal2nix` on each cabal file it finds to generate a `default.nix` in that directory.

**Comment by NorfairKing** [comment]
Here's how I would implement it:
```
cabal2nix = {
            enable = true;
            name = "cabal2nix";
            files = "\\.cabal$";
            entry = "${pkgs.writeShellScript "cabal2nix-hook" ''
              for cabalFile in $*
              do
                dir="$(dirname $cabalFile)"
                defaultFile="$dir/default.nix"
                ${pkgs.cabal2nix}/bin/cabal2nix "$cabalFile" > "$defaultFile"
                ${pkgs.nixpkgs-fmt}/bin/nixpkgs-fmt "$defaultFile"
              done

            ''}";
          };
```

**Comment by NorfairKing** [comment]
I just realised the formatting problem can be solved by ignoring files called `default.nix` in the formatter hook but that's a bit dirty.

**Comment by roberth** [comment]
A few hooks pull extra settings from options named `settings.<hookname>.foo`, so you could make the choice of nix formatter configurable. That's still duplicate configuration, but at least it'd work for all formatters. For a real solution, we either need a way to safely reinvoke pre-commit on the file, or create an option to explicitly represent the _choice_ of nix formatter, which is kind of a breaking change.

**Comment by NorfairKing** [comment]
@roberth Having the user use the `excludes` config is good enough for me for now. See the PR: #170
