### ISSUE TITLE
Inclusion of revive breaks use of current stable (22.05)

### ISSUE THREAD

**Issue by JayRovacsek** [cachix/pre-commit-hooks.nix#185]
G'day!

Firstly, thanks to all contributors for this project - you're doing awesome work!

My issue:

Recently shellChecks within a flake I'm using have become broken due to the changes associated with [this commit](https://github.com/cachix/pre-commit-hooks.nix/commit/08d848d10e075c85a9246c39bb20c4a86db34e79). This break is due to the fact I've set a `nixpkgs.follows` within my [pre-commit-hooks inputs](https://github.com/JayRovacsek/nix-config/blob/7abada4d2fb76d8c25915c74b27038949e10a86a/flake.nix#L33) as following current stable nixpkgs (22.05)

This is problematic as `revive` does not seem to currently appear to be within the 22.05 package set ([unstable](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=revive) vs [22.05](https://search.nixos.org/packages?channel=22.05&from=0&size=50&sort=relevance&type=packages&query=revive)) and [no issues exist to create it currently](https://github.com/NixOS/nixpkgs/issues?q=is%3Aissue+is%3Aopen+revive). I am aware we're looking at the stabilisation/release of 22.11 very shortly but would like to still raise this issue in the interim as there may be more people impacted by this change than myself.

For now I can either utilise unstable or revert my flake inputs in relation to pre-commit-hooks to resolve this but wanted to raise awareness of the issue: given the conversation in the [associated merge](https://github.com/cachix/pre-commit-hooks.nix/pull/178) should documentation be updated to reflect the recommendation/requirement of unstable in this flake?

**Comment by JayRovacsek** [comment]
FWIW: Happy to contribute to README if considered a suitable option to make explicit and clear unstable requirement :+1:

**Comment by domenkozar** [comment]
I'll look into this, it should only fail if you're using revive.

**Comment by roberth** [comment]
`callPackage` performs a strict lookup.

I guess you could avoid `callPackage` and do something predictable like `tools = pkgs // extraTools; checkedTools = { inherit (pkgs) ...; } // tools;` and then only build `checkedTools` in CI.

**Comment by domenkozar** [comment]
Could you try if https://github.com/cachix/pre-commit-hooks.nix/pull/186 fixes it?
