### ISSUE TITLE
"WARNING: pre-commit-hooks.nix: .git not found; skipping installation."

### ISSUE THREAD

**Issue by tartavull** [cachix/pre-commit-hooks.nix#195]
Hello,

Thank you for this awesome package.
I can't grasp why I'm getting the error in the title of this  issue.  I would appreciate any help debugging this.
My `shell.nix` lives inside `/nix`.

**Comment by domenkozar** [comment]
do you have the latest master version?

**Comment by domenkozar** [comment]
This was fixed on master.
