### ISSUE TITLE
Redesign module options

### ISSUE THREAD

**Issue by domenkozar** [cachix/pre-commit-hooks.nix#196]
Something like:

```nix
{
  git.hooks.pre-commit.shellcheck.enable = true;
  git.hooks.push.shellcheck.enable = true;
}
```

cc @roberth

**Comment by roberth** [comment]
```diff
-  git.hooks.pre-commit.shellcheck.enable = true;
+  hooks.pre-commit.shellcheck.enable = true;
```

This way devenv can import it using `git = mkOption { type = submodule pre-commit-hooks-module; }` and the flake parts module can import it in its own way. The latter needs to be explicit about the implementation in the prefix and `pre-commit.settings.git.hooks` would kinda suck.
Isn't this the status quo actually?

Anyway, another nice thing would be to do

```nix
{
options.hooks = mkOption {
  type = submodule {
    freeformType = types.attrsOf hookModule;
  };
};
}
```

and then declare built in hooks as something like

```nix
{
options.hooks.nixpkgs-fmt = mkOption {
  type = submodule {
    imports = [ hookModule ];
    options.some-setting = mkOption ...;
  };
};
}
```

thereby adding the individual hooks in the option docs, and removing the need for a separate settings namespace.

**Comment by roberth** [comment]
The redesigned pattern should have a `package` option, so the `tools` indirection becomes unnecessary, and overlays can be avoided. Refs https://github.com/cachix/pre-commit-hooks.nix/issues/204#issuecomment-1334165738

**Comment by domenkozar** [comment]
Eventually I'd like the interface to be:

```
  hooks.ormolu.enable = true;
  hooks.ormolu.package = pkgs.ormolu;
  hooks.ormolu.settings.defaultExtensions = [ "lhs" "hs" ];
```

**Comment by domenkozar** [comment]
Merged to master!
