### ISSUE TITLE
Tools are no longer exposed to non-flake projects

### ISSUE THREAD

**Issue by sd234678** [cachix/pre-commit-hooks.nix#197]
Non-flake projects referencing this project are no longer able to access tools used by this project (such as individual formatters etc.) as of 24c959a4d134d4f2b08832375bf0b8887cfcf490, since only `run` is exposed in default.nix.

Flake projects can still access these tools through the `packages` attribute. Is this intentional?

**Comment by domenkozar** [comment]
That's not intentional, packages should also be exported there.

**Comment by domenkozar** [comment]
could you try https://github.com/cachix/pre-commit-hooks.nix/pull/199
