### ISSUE TITLE
Add docs, examples for overriding provided hooks

### ISSUE THREAD

**Issue by domenkozar** [cachix/pre-commit-hooks.nix#2]
Something like:

```nix
nix-pre-commit-hooks.run {
  src = gitignoreSource ./.;
  hooks = ["shellcheck"];
}
```

**Comment by roberth** [comment]
I'd be perfectly happy to require the YAML to be JSON and DRY it with `builtins.fromJSON`

**Comment by roberth** [comment]
Even better: generate a YAML from with builtins.toJSON. Best: use the module system.

**Comment by roberth** [comment]
If this is about download size, I wrote a thing https://github.com/roberth/nix-lazy-env

**Comment by domenkozar** [comment]
Nice! Yes, partially it's about the download size and partially it's for providing additional hooks.

**Comment by domenkozar** [comment]
This seems nice and simple: https://github.com/kampka/pre-commit-hooks

**Comment by domenkozar** [comment]
Let's leave this one open as it needs some examples in the docs.

**Comment by timokau** [comment]
For what it's worth, I came up with this config to run the black python code formatter:

```nix
let
  nix-pre-commit-hooks = import (builtins.fetchTarball "https://github.com/cachix/pre-commit-hooks.nix/tarball/master");
  pkgs = import <nixpkgs> {};
in {
  pre-commit-check = nix-pre-commit-hooks.run {
    src = ./.;
    hooks = {
      shellcheck.enable = true;
      black = {
        enable = true;
        name = "black";
        description = "Format Python files";
        entry = "${pkgs.python3.pkgs.black}/bin/black --check";
        types = ["python"];
      };
    };
  };
}
```

That could probably be used as an example. I'm wondering: Why do you use the module-system here? Wouldn't it be easier and more convenient to just use a list of attrsets, with some attrsets pre defined?

**Comment by domenkozar** [comment]
I'll let that @roberth answer, I was also more for simple design of attrsets and defaults.

**Comment by roberth** [comment]
With the module system you get
 - type checking, improving error messages
 - a framework for documentation
 - configurations merging and overrides, so you can have defaults for your team for example

**Comment by domenkozar** [comment]
https://github.com/cachix/pre-commit-hooks.nix#custom-hooks is now there
