### ISSUE TITLE
Add pre-commit-hook-ensure-sops?

### ISSUE THREAD

**Issue by nialov** [cachix/pre-commit-hooks.nix#208]
Hey,

I have packaged and configured [`pre-commit-hook-ensure-sops`](https://github.com/yuvipanda/pre-commit-hook-ensure-sops) that checks the repository for improperly managed `sops` secrets. It is useful for paranoid [`sops-nix`](https://github.com/Mic92/sops-nix) users.

See here: https://gist.github.com/nialov/867d96761f2a68168e09a10d8fe6f63a

Should I do a pull request or are these smaller, quite specialized hooks, wanted in `pre-commit-hooks.nix`?

**Comment by domenkozar** [comment]
Would be good to have it here!

**Comment by nialov** [comment]
Cool, I will make a pull request (hopefully) over the weekend.
