### ISSUE TITLE
alejandra: use `--check`

### ISSUE THREAD

**Issue by NobbZ** [cachix/pre-commit-hooks.nix#218]
The current implementation of the `alejandra` hook runs `alejandra` and changes the files on the filesystem, somehow checking for dirty/changed files after that.

I do not like when git hooks actually alter the repo, they should simply signal "failure" or "success" through the exit code.

To solve this issue one can use `--check` with `alejandra` though there is no option exposed to enable that.

Please make `--check` the default and/or add an option to opt-in/out.

**Comment by totoroot** [comment]
I did not change the defaults, but introduced a `check` option that can be used to achieve what you were trying to do.
More information on that can be found in #353.
