### ISSUE TITLE
alejandra: provide a `package` option

### ISSUE THREAD

**Issue by NobbZ** [cachix/pre-commit-hooks.nix#219]
Currently some `alejandra` is used, and for the user it is not clear from where it is taken.

Please document how the default `alejandra` is picked and give an option to easily override it.

**Comment by NobbZ** [comment]
Similar restrictions seem to apply for all other hooks.

Can't currently use the rust based ones as they seem to use rust from `nixpkgs`, while I am developing using a nightly rust compiler…

**Comment by domenkozar** [comment]
See https://github.com/cachix/devenv/blob/main/src/modules/languages/rust.nix#L59 how overrides can be done

**Comment by purefn** [comment]
I'm currently trying this with 

```
  pre-commit-check = nix-pre-commit-hooks.run {
    src = ./.;
    excludes = ["^vendor/"];
    hooks = {
      ormolu.enable = true;
      purs-tidy.enable = true;
    };
    settings = {
      ormolu.defaultExtensions = [ "TypeApplications" "BangPatterns" "QuasiQuotes" "TemplateHaskell" ];
    };
    tools =
      let
        mkOverrideTools = lib.mkOverride (lib.modules.defaultOverridePriority - 1);
      in {
        purs-tidy = mkOverrideTools purs-tidy;
        ormolu = mkOverrideTools haskell-pkgs.ormolu;
      };
  };
```

to get the version of ormolu that we've been using and it doesn't seem to be working as expected. What am I missing?

**Comment by purefn** [comment]
Ignore my comment. It was using the version I was telling it. It was elsewhere that wasn't using the version I was expecting. Sorry!
