### ISSUE TITLE
Support for mono-repos?

### ISSUE THREAD

**Issue by roman** [cachix/pre-commit-hooks.nix#224]
### Context

As a developer that works on a project inside a monorepo
I would like to inject a pre-commit hook on a subdirectory of the git repo
So that I can take advantage of the fantastic pre-commit-hooks.nix tool

### Problem

When we have a `flake.nix` file with a pre-commit setup that runs the `shellHook` on a sub-directory of the repository, the `pre-commit-hooks.nix` tool doesn't install the pre-commit hooks. Instead, it reports:

> WARNING: pre-commit-hooks.nix: .git not found; skipping installation.

### Current behavior

It seems `pre-commit-hooks.nix` assumes that the `flake.nix` file and the `.git` folder are in the same directory.

### Expected behaviour

Ideally, we can get a pre-commit-hook installation that works only on the sub-directory of the repository that contains the flake. 

Is this possible?

**Comment by domenkozar** [comment]
It's currently not possible, but that could be taken into account together with #196

**Comment by roman** [comment]
I think I can unblock with some less demanding change. I notice that if we make the `.git` directory check in the installation script traverse parent directories, things work as expected.

I created a [PR](https://github.com/cachix/pre-commit-hooks.nix/pull/225) with such a change. The PR is currently failing as it requires a [package that I added to `nixpkgs`](https://github.com/NixOS/nixpkgs/pull/210256).

**Comment by tennox** [comment]
I dug into the changes linked here - up until https://github.com/cachix/git-hooks.nix/commit/3973f374042c9c6dc80d39e7a6805242256608ad, but I can't figure out how to use pre-commit hooks in a monorepo :thinking:  :disappointed: 
Any pointers?
