### ISSUE TITLE
hook specific excludes don't end up in generated json

### ISSUE THREAD

**Issue by domenkozar** [cachix/pre-commit-hooks.nix#23]
most likely broken in recent global excludes PR /cc @roberth

**Comment by roberth** [comment]
They're part of the "defaults" in the generated hooks repo in the nix store. This is why they don't show up in the `.pre-commit-config.yaml`.

**Comment by domenkozar** [comment]
It seems like `.pre-commit-hooks` is not needed anymore now that we can just generate whole `.pre-commit-config`

**Comment by roberth** [comment]
We do need a gc root though and `-config.yaml` can not be a symlink.
The gc root can doesn't have to be in pre-commit repo format though and I suspect we're hitting some sort of cache bug with the current solution.

**Comment by domenkozar** [comment]
fixed in master
