### ISSUE TITLE
The `hpack` hook seems broken in several different ways

### ISSUE THREAD

**Issue by Niols** [cachix/pre-commit-hooks.nix#235]
Hi there, and thank you very much for this super practical piece of software; I'm a big fan!

I have observed very peculiar behaviours of the `hpack` hook on various repositories that I am using, in particular [tweag/pirouette](https://github.com/tweag/pirouette) and [tweag/plutus-libs](https://github.com/tweag/plutus-libs). In Pirouette, the hook triggers but is always happy, even when it really shouldn't. In plutus-libs, the hook simply seems to never trigger. I traced it down to two different issues.

I am happy to suggest a PR for these things.

### About the `hpack-dir` utility

This repository contains a `hpack-dir` utility running `hpack` on all the `package.yaml` files:

https://github.com/cachix/pre-commit-hooks.nix/blob/7bdf85f6bbef581eb687838d19f2b35a4c9d77f0/nix/hpack-dir/default.nix#L3-L9

This script has two problems. First, it requires the `hpack` utility to be present in the PATH, which is not necessarily the case. I suspect it is a simple mistake because the Nix file takes an `hpack` argument as input. We should probably simply replace the call to `hpack` by a call to `${hpack}/bin/hpack`.

Second, this script fails silently. This is due to the use of `find` and there is no good way around it. I would personally go for
```sh
find . -type f -name package.yaml | while read -r file; do
    hpack --force $flag "$file"
done
```
(or actually `${hpack}/bin/hpack`) in conjunction to a `set -e` at the beginning of the script. This will ensure that other errors of `hpack`, for whatever reason, would stop the script. In general, `hpack` doesn't fail so it shouldn't really be an issue.

---
---
---

_Everything after this point turns out to be wrong; very sorry about that._

### About the `files` pattern

The `hpack` hook is defined as follows:

https://github.com/cachix/pre-commit-hooks.nix/blob/7bdf85f6bbef581eb687838d19f2b35a4c9d77f0/modules/hooks.nix#L420-L435

and it seems to never trigger on `package.yaml` or `*.cabal` files in plutus-libs. I have experimented a bit and it seems to me that the `files` pattern applies to the _path_ in the repository. The pattern:

```nix
   files = "(\\.l?hs(-boot)?$)|(^[^/]+\\.cabal$)|(^package\\.yaml$)"; 
```

then simply does not trigger when `package.yaml` or `*.cabal` are not at the root of the repository. I have experimented with simply `package\\.yaml$` and the less permissive `(^package\\.yaml$)|(/package\\.yaml$)` and both seem to trigger just fine. I don't have a good reference in the documentation of pre-commit, so double checks are most welcome.

### About the idea to run on every `package.yaml`

Actually, while I'm at it, let me mention this: as of now, we run `hpack` on all the `package.yaml` files of the repository, which includes ignored files and in particular all the `package.yaml` files in `dist-newstyle`. I'm not sure that it's an issue, but it is in any case not the cleanest. This does not affect any kind of run that copies to the Nix store first, such as `nix flake check`.

**Comment by Niols** [comment]
For reference and if interested, here are two pull requests that implement the addition of a `hpack` hook into our two projects. The custom hook is inspired by the things I describe above.

- https://github.com/tweag/pirouette/pull/177
- https://github.com/tweag/plutus-libs/pull/226

**Comment by Niols** [comment]
Actually, the `files` pattern seems just fine, the problem was coming from something else different on our end. I will edit the issue description accordingly.

**Comment by domenkozar** [comment]
Happy to merge a PR and thanks for throughout analysis!
