### ISSUE TITLE
Feature request: several OCaml-related hooks

### ISSUE THREAD

**Issue by Niols** [cachix/pre-commit-hooks.nix#237]
I am using several [OCaml](https://ocaml.org/)-related hooks for my personal projects. I think it might be worth making them available to the public through this repository. In particular, I use:

- An `opam lint` hook that checks [OPAM](https://opam.ocaml.org/) (OCaml Package Manager) configuration files.
  ```nix
  {
    enable = true;
    name = "opam lint";
    entry = "${pkgs.opam}/bin/opam lint";
    files = "\\.opam$";
  }
  ```

- An `ocp-indent` hook that checks that [ocp-indent](https://ocaml.org/p/ocp-indent/), an indenter for OCaml, is happy with the OCaml files.
  ```nix
  {
    enable = true;
    name = "ocp-indent";
    entry = "${pkgs.ocamlPackages.ocp-indent}/bin/ocp-indent --inplace";
    files = "(\\.ml$)|(\\.mli$)";
  }
  ```

- A `dune/opam sync` hook that checks that the OPAM files generated by [Dune](https://dune.readthedocs.io/en/stable/), an OCaml build system able, are in sync with the ones in the repository. (Similarly to how the `hpack` hook goes.)
  ```nix
  {
    enable = true;
    name = "dune/opam sync";
    entry = let
      dune-build-opam-file = pkgs.writeShellApplication {
        name = "dune-build-opam-file";
        runtimeInputs = [ pkgs.pkgsBuildBuild.ocaml ];
        text = ''
          set -e
          find . -type f -name '*.opam' | while read -r file; do
              ${pkgs.dune_3}/bin/dune build "$file"
          done
        '';
      };
    in "${dune-build-opam-file}/bin/dune-build-opam-file";
    files = "(\\.opam$)|((^|/)dune-project$)";
    pass_filenames = false;
  }
  ```

- I am not using it yet, but I will soon add a hook to my projects to use [Topiary](https://github.com/tweag/topiary), a formatter supporting OCaml, among other formats. I could also add a hook for that.

What do you think? Would it make sense to add them? I could open pull requests to add them if you are interested.

**Comment by domenkozar** [comment]
It would be great to have them!
