### ISSUE TITLE
Add checkmake

### ISSUE THREAD

**Issue by sir4ur0n** [cachix/pre-commit-hooks.nix#251]
Please add [checkmake](https://github.com/mrtazz/checkmake), a linter for Makefiles.

* `checkmake` is available on Nixpkgs
* The check command is `checkmake <makefile>`

**Comment by Niols** [comment]
From the look of it, `checkmate` has a rather simple and usual interface. Therefore, a `pre-commit-hooks.nix` configuration with `hooks` looking like:

```nix
{
  hpack.enable = true; ## or whatnot
  ## ... other hooks
  checkmake = {
    name = "checkmake";
    types = [ "makefile" ];
    entry = "${pkgs.checkmake}/bin/checkmake";
  };
}
```

should work? (with `pkgs` being `nixpkgs` specialised for your system) I don't have many projects to try it on, but if it works for you I'll happily write a PR to integrate this.

**Comment by sir4ur0n** [comment]
@Niols I needed to add `enable = true;` but otherwise it seems to work fine :+1: :bow:

**Comment by Niols** [comment]
Hey @sir4ur0n. My PR #274 has been merged, so `pre-commit-hooks.nix` now supports `checkmake` out of the box. You can therefore:

1. Update your flake lock file for `pre-commit-hooks.nix`.
2. If `pre-commit-hooks.nix`'s `nixpkgs` input follows something else, make sure this one is recent enough to contain `checkmake` 0.2.2.
3. Replace the configuration above by just `checkmake.enable = true`.
4. Enjoy.

**Comment by sir4ur0n** [comment]
Thank you @Niols it seems to work like a charm!
