### ISSUE TITLE
flake update in CI

### ISSUE THREAD

**Issue by MangoIV** [cachix/pre-commit-hooks.nix#259]
would it be possible to add [the determinate system flake update action?](https://github.com/DeterminateSystems/update-flake-lock)

If you want, I can just add it, only downside would be that the owner would have to add a GitHub token to make it possible for the action to trigger other actions. 

I have done this [here](https://github.com/alpmestan/ghc.nix/) and it works quite nicely

**Comment by domenkozar** [comment]
I added renovate today.
