### ISSUE TITLE
`.pre-commit-config.yaml` is not always installed to project root

### ISSUE THREAD

**Issue by srid** [cachix/pre-commit-hooks.nix#267]
**How to reproduce**

Start `nix develop` from inside of a sub-directory (not project root).

**Current behaviour**

`.pre-commit-config.yaml` gets added to _that sub-directory_

**Expected behaviour**

`.pre-commit-config.yaml` should always be added to project root (where `flake.nix` is) regardless of the $PWD from which `nix develop` was launched.

**Proposed solution**

Have an optional dependency on https://github.com/srid/flake-root and if the user has enabled it, have the devShell shellHook (of #266) do a:

```nix
shellHook = ''
  FLAKE_ROOT="''$(${lib.getExe config.flake-root.package})"
  (cd FLAKE_ROOT && ${config.pre-commit.installationScript})
''
```

**Comment by srid** [comment]
Alternatively, the `installationScript` can just check for the existence of `$FLAKE_ROOT` and `cd` to it automatically. This way it will work for all cases, regardless of flake-parts.

**Comment by domenkozar** [comment]
Should we just check for `.git` and add it there?

**Comment by srid** [comment]
@domenkozar That's actually even better. And do you mean add the yaml file *inside* `.git` folder?

**Comment by srid** [comment]
@domenkozar Does this look good? https://github.com/cachix/pre-commit-hooks.nix/pull/271
