### ISSUE TITLE
`pre-commit` script does something different than the check

### ISSUE THREAD

**Issue by MangoIV** [cachix/pre-commit-hooks.nix#278]
see this failure: https://builds.sr.ht/~mangoiv/job/973664

- `pre-commit run -a` passes but `nix flake check` fails. Both seem to use the same `fourmolu.yaml` so I think this should not be the reason. Perhaps different flags are passed?

**Comment by MangoIV** [comment]
yeah no I don't have an idea where this could come from. when I run `fourmolu` locally, I also get the result I get in the check although the reason there could be that it's actually a different `fourmolu` version there, which should not be the case wrt `pre-commit` and the check.

**Comment by edrex** [comment]
Similar symptom (`nix flake check` fails while `pre-commit run --all-files` succeeds) in https://github.com/cachix/pre-commit-hooks.nix/issues/277. Seems likely the same root cause.

**Comment by domenkozar** [comment]
Maybe it's different pre-commit version (a bug recently fixed)?

**Comment by MangoIV** [comment]
I’ll try enabling the check and upgrading pchs today :)

**Comment by MangoIV** [comment]
it passes now! I think this makes this issue fixed, at least for me. If @edrex' issue persists, then you can just reopen it, I guess.
