### ISSUE TITLE
Unable to pass a config file to the typos hook

### ISSUE THREAD

**Issue by SrEstegosaurio** [cachix/pre-commit-hooks.nix#291]
It's currently impossible to configure the [typos](https://github.com/crate-ci/typos) hook, neither via this or by toml files _(see: https://github.com/crate-ci/typos/blob/master/docs/reference.md )_. 

This is rather inconvenient since typos keeps complaining about errors on a png, among other non-text files.

Ideally nixifying the configuration would be the solution, but as that takes some time and effort, an way to pass the `--config PATH` option to typos might work well for now. In fact I believe that both options can co-exist.

P.S: Thanks for maintaining this project! :)

**Comment by totoroot** [comment]
@SrEstegosaurio @Stunkymonkey Could you please check whether [what got merged into the master branch](https://github.com/cachix/pre-commit-hooks.nix/pull/333) yesterday was what you were looking for? :)

As suggested, both options now co-exist.

**Comment by Stunkymonkey** [comment]
thanks @totoroot  for fixing it.
