### ISSUE TITLE
[question] Difference with other pre-commit framwork?

### ISSUE THREAD

**Issue by Freed-Wu** [cachix/pre-commit-hooks.nix#302]
What is the difference between this project and [pre-commit](https://github.com/pre-commit/pre-commit)? That is, what is this project can do while other project cannot do, and what is other project can do and this project cannot do? It can help users know this project more and helpful for them to choose appropriate project in different situations. TIA!

**Comment by loicreynier** [comment]
This project is not an alternative to pre-commit but an interface to install and manage pre-commit hooks with Nix. It is used to integrate pre-commit in a Nix environment/project.

**Comment by Freed-Wu** [comment]
OK, I see :+1:
