### ISSUE TITLE
Document some of the questions raised

### ISSUE THREAD

**Issue by roberth** [cachix/pre-commit-hooks.nix#32]
For example everything from
https://github.com/cachix/pre-commit-hooks.nix/issues?utf8=%E2%9C%93&q=+author%3APierreR

**Comment by bbigras** [comment]
The link doesn't show anything.

**Comment by roberth** [comment]
Fixed the link.

**Comment by domenkozar** [comment]
also https://github.com/cachix/devenv/issues/426#issuecomment-1439910460

**Comment by domenkozar** [comment]
Should be good now, open an issue for specific things please.
