### ISSUE TITLE
pre-commit config references a broken symlink in nix store

### ISSUE THREAD

**Issue by alejandro-angulo** [cachix/pre-commit-hooks.nix#336]
**Describe the bug**
When trying to set `pre-commit.settings.prettier.binPath` my generated `.pre-commit-config.yaml` file ends up with an entry referencing a broken symlink in my nix store.

Here's an example of generated config file https://gist.github.com/alejandro-angulo/a467575f910ea4bb7b837d913f8e44af

**To reproduce**
I've created a repo to reproduce this bug: https://github.com/alejandro-angulo/devenv-pre-commit-test/tree/59e2e768d472d64e39e9d47992fd54c83cfb9d31

```
git clone https://github.com/alejandro-angulo/devenv-pre-commit-test.git
cd devenv-pre-commit-test
nix develop --impure  # or `direnv allow`
pre-commit run prettier --files test.js
```
On my machine I get this output
```
❯ pre-commit run prettier --files test.js
prettier.................................................................Failed
- hook id: prettier
- exit code: 1

Executable `/nix/store/apjv7ccblhywdccadbpb2w0ghd0k20fb-prettier` not found

❯ l /nix/store/apjv7ccblhywdccadbpb2w0ghd0k20fb-prettier
lrwxrwxrwx 28 root 31 Dec  1969  /nix/store/apjv7ccblhywdccadbpb2w0ghd0k20fb-prettier -> ../prettier/bin/prettier.cjs
```

Notice that the symlink resolves to a directory `/nix/store/prettier/....` (this does not exist).

I expected the executable to match the value I see in `nix repl`

```
nix-repl> outputs.devShells.x86_64-linux.default.config.pre-commit.settings.prettier.binPath
/nix/store/a80wmqkzayj1kvrllif6db3c0skklymr-source/node_modules/.bin/prettier
```

**Version**
devenv: 0.6.3

**Comment by domenkozar** [comment]
I transfered it to the right repo. Thanks!

**Comment by alejandro-angulo** [comment]
Oh I found out that I can instead have `pre-commit.settings.prettier.binPath = self.outPath + "/node_modules/.bin/prettier"` and it works as I expected.
