### ISSUE TITLE
Shellcheck: files are not picked up correctly

### ISSUE THREAD

**Issue by roberth** [cachix/pre-commit-hooks.nix#35]
`types: bash` only finds `#!/bin/bash` shebangs it seems.

It should pick up:
 - `*.sh`
 - `#!/bin/bash` (this one seems to work)
 - `#!/bin/sh`
 - `#!/usr/bin/env bash`
 - `#!/usr/bin/env sh`
 - `#!/usr/bin/env nix-shell`+`#!.*nix-shell.*-i bash.*`

**Comment by domenkozar** [comment]
This should probably be reported to https://github.com/pre-commit/pre-commit, since filtering isn't advanced enough to cover all these cases.

**Comment by blaggacao** [comment]
Not even there, but here: https://github.com/chriskuehl/identify

**Comment by blaggacao** [comment]
Please review & approve there: https://github.com/chriskuehl/identify/pull/127

**Comment by blaggacao** [comment]
After those changes, `#!.*nix-shell.*-i bash.*` this unconventionak format would not be supported by `identify`, yet. But maybe ther is an argument for supporting it cleanly to be made upstream.

**Comment by blaggacao** [comment]
Yoou! Looks like striking this ticket off the list comes within reach :partying_face:

**Comment by asottile** [comment]
OP's message implies this is using `types: [bash]` -- you probably want `types: [shell]` fwiw

**Comment by blaggacao** [comment]
@asottile 
> OP's message implies this is using types: [bash] -- you probably want types: [shell] fwiw

Oh thank you! Actually the following commit was meant not to hit on eg. `csh` which is not supported by shellcheck. I can already update the corresponding draft PR here. Is there a possibility to cut a release for `identify` soonish?

https://github.com/chriskuehl/identify/pull/129

**Comment by asottile** [comment]
I was going to merge the nix stuff first

**Comment by roberth** [comment]
We can use this list to set the right `types` https://github.com/koalaman/shellcheck/blob/cfd68ee0c2ebfd0ab08a1d4bf628162b454dc207/src/ShellCheck/Parser.hs#L3236

**Comment by roberth** [comment]
Encountered this just now. Not sure if everything is up to date, but I suppose this may help others. My error:
```
In scripts/generate-nix line 1:
#!/usr/bin/env nix-shell
^-- SC1008: This shebang was unrecognized. ShellCheck only supports sh/bash/dash/ksh. Add a 'shell' directive to specify.

```

Successful workaround:

```
#!/usr/bin/env nix-shell
# shellcheck disable=SC1008
#!nix-shell -i bash
#!nix-shell ../shell.nix

```
