### ISSUE TITLE
Is there a way to get the packages used by hooks as nix devshell inputs?

### ISSUE THREAD

**Issue by Janik-Haag** [cachix/pre-commit-hooks.nix#356]
Basically what I want to do is define the pre-commit-hooks with this project and then want to add them to my devshells buildInputs. 
Is there a way to do that, that isn't writing them double?

**Comment by domenkozar** [comment]
This seems like a good candidate for #196

**Comment by tljuniper** [comment]
With #196 implemented, is this now possible or is there something else that needs to be done to get access to the packages used in pre-commit-hooks?

**Comment by tljuniper** [comment]
Wow, that was fast! Thanks for taking a look!

The new `flake.nix` example in the README currently fails with `error: attribute 'enabledPackages' missing` when I paste it into an empty directory and run `nix develop`.

The `default.nix` + `shell.nix` examples fail with `error: undefined variable 'pkgs'`.

**Comment by domenkozar** [comment]
Can you try again with the flakes?

**Comment by tljuniper** [comment]
Works now. Thank you so much!

**Comment by danielgafni** [comment]
ohh was wondering why was `enabledPackages` missing too.. I just had to update the flake :)
