### ISSUE TITLE
Help merging with exisiting shellHook

### ISSUE THREAD

**Issue by KyleOndy** [cachix/pre-commit-hooks.nix#42]
I acknowledged this is more of a support request than an issue as I am still learning how the nix language works. If there is a better place for this, please point me that way.

---

In step 3 of the `README` [1] is appears we are setting the `shellHook` to some computed value `.pre-commit-check`. How would I merge this which an existing `shellHook`, something like [2]?

[1] 
```nix
 (import <nixpkgs> {}).mkShell {
   inherit ((import ./default.nix).pre-commit-check) shellHook;
 }
```

[2]
```nix
shellHook = ''
  export FOO=bar
'';
```

**Comment by roberth** [comment]
You could use string interpolation like this:

```
mkShell { # or similar
shellHook = ''
  export FOO=bar
  ${(import ./default.nix).pre-commit-check.shellHook}
'';
}
```

**Comment by KyleOndy** [comment]
Ah. That feels really obvious now. Thanks for the help @roberth. I really appreciate it!
