### ISSUE TITLE
hpack hook should trigger on any changes to haskell code

### ISSUE THREAD

**Issue by fiadliel** [cachix/pre-commit-hooks.nix#43]
For hpack, cabal file generation is not only dependent on `package.yaml`, but also on the full list of Haskell modules in `source-dirs` (in many projects, this is the most common cause of cabal file invalidation).

So, hpack pre-commit should trigger due to changes in any hs/lhs file.

**Comment by domenkozar** [comment]
@hyperfekt

**Comment by fiadliel** [comment]
I had a quick look at this; it seems like hpack returns a zero exit code when updating; so the wrapper needs to be a little more complex. It doesn't even vary its output for unchanged/updated files. Bad hpack.

So... in my mind, what's needed might be to grab `name` from `package.yaml` to figure out which cabal file is being generated, save existing copy of that file; run `hpack`, compare new version with existing, spit out appropriate exit code.

**Comment by hyperfekt** [comment]
@fiadliel pre-commit already compares the old file with the new one.

**Comment by roberth** [comment]
Cabal files can have any name. It just looks for `*.cabal`. You could have `package.cabal` everywhere if you'd like.

**Comment by fiadliel** [comment]
@hyperfekt Ah good. I had a parse error on `must exit nonzero on failure or modify files`. I'm trying to get something working locally, so I guess I got something else wrong.

**Comment by hyperfekt** [comment]
@fiadliel Make sure that the cabal file is already in the index.

**Comment by fiadliel** [comment]
Okay, I have something that seems to work with
```nix
  wrapped-hpack = pkgs.writeShellScript "wrapped-hpack" ''
    exec ${pkgs.haskellPackages.hpack}/bin/hpack --force .
  '';
```
and
```nix
    hpack-fixed = {
      enable = true;
      name = "hpack";
      description = "Run hpack on package.yaml";
      entry = "${wrapped-hpack}";
      files = "(\\.l?hs$)|(^[^/]+\\.cabal$)|(^package\\.yaml$)";
    };
```

It's probably worth adding support for the `pass_filenames` pre-commit parameter, to avoid the extra layer of indirection.
