### ISSUE TITLE
Support specifying stages

### ISSUE THREAD

**Issue by blaggacao** [cachix/pre-commit-hooks.nix#49]
For speedy development, I'd configure certain hooks for different stages.

A common example:

- run pre-commit hooks on the `prepush` stage (to make sure only "clean" stuff gets remoted)
- don't run anything on _commit_ to avoid disrupting _developer's **flow**_
- alias `prepush` hooks from a justfile, so developer can run - e.g. - `just fmt` conscientiously and avoid surprises at `git push` (promote the stimulus of being in control)

Therefore, I'd need to configure:
- either `hook = { stages = ["manual", "push"] }`
- or something global `... run { ...; stages = [ "manual", "push" ] }`

**Comment by domenkozar** [comment]
I'm not entirely (yet) convinced that should be part of the API.

You can achieve this yourself with the current API, but it would be nice to have a snippet people can reuse.

**Comment by blaggacao** [comment]
Do you refer to?
- global: https://github.com/cachix/pre-commit-hooks.nix/blob/master/modules/pre-commit.nix#L261
- per hook: https://github.com/cachix/pre-commit-hooks.nix/blob/master/modules/pre-commit.nix#L33

I'll check if I can get that to work, thanks.

**Comment by domenkozar** [comment]
It seems like this would work by specifying https://pre-commit.com/#top_level-default_stages and stages.

Should be quick to add.

**Comment by blaggacao** [comment]
That's correct, since I don't like using commit stages I usually did:
`default_stages: ["manual", "push"]`

**Comment by blaggacao** [comment]
> Should be quick to add.

That was a _trick_ :hand: :stuck_out_tongue_winking_eye:
