### ISSUE TITLE
Make WARNING colourful

### ISSUE THREAD

**Issue by blaggacao** [cachix/pre-commit-hooks.nix#54]
```console
[...]
nix-pre-commit-hooks: updating /home/blaggacao/ghq/git.p1.rocks/gitops/chore.k8s repo
nix-pre-commit-hooks: WARNING: Refusing to install because of pre-existing .pre-commit-config.yaml
    1. Translate .pre-commit-config.yaml contents to the new syntax in your Nix file
        see https://github.com/hercules-ci/nix-pre-commit-hooks#getting-started
    2. remove .pre-commit-config.yaml
    3. add .pre-commit-config.yaml to .gitignore
[...]
```

I overlook it still every time which, mainly because of the `[...]`.

This again, leads to unintended consequential mistakes.
In the most hilarious cases it was chaining up to 30 minutes.

**Comment by domenkozar** [comment]
Probably the best we can do is `exit 1`, what do you mean with chaining up?

**Comment by blaggacao** [comment]
> chaining up

-> muy ignorance & frustration 😉 

I like `exit 1` as an alternative.

If I understand correctly, dies it mea s that if pre-commit fails, then the environment as a whole is fails? Or would it still leave us with a oartially functioning environmen?

**Comment by domenkozar** [comment]
Exactly, the environment wouldn't activate. I think that's best because that leaves clear expectations.

**Comment by blaggacao** [comment]
I'm closing this as not immediatly actionable. If I fsitll find inconvenience about rhe current behaviour in the future, I will do a PR.

**Comment by domenkozar** [comment]
Adding `exit 1` seems actionable to me, but we have to turn the warning into an error.
