### ISSUE TITLE
Expose as a flake

### ISSUE THREAD

**Issue by Mic92** [cachix/pre-commit-hooks.nix#57]
Currently its not possible to use this with `nix develop` because it internally re-imports nixpkgs:

```
error: --- EvalError --------------------------------------------------------------------------------- nix
at: (90:39) in file: /nix/store/ma3b77vjls3qrznwh66ix5ivvybx6003-source/pkgs/top-level/impure.nix

    89|                 else (if args ? localSystem then {}
    90|                       else { system = builtins.currentSystem; }) // localSystem;
      |                                       ^
    91| })

attribute 'currentSystem' missing
(use '--show-trace' to show detailed location information)
direnv: export +IN_NIX_SHELL ~PATH
```

**Comment by roberth** [comment]
It works fine if you import the modules directly. Not saying you should do that, but that means it's not far off.

**Comment by Mic92** [comment]
I don't think the modules can be imported directly. It's too tightly coupled too niv and inject overlays, which cannot be easily overwritten.

**Comment by roberth** [comment]
It's not that [bad](https://github.com/hercules-ci/project.nix/blob/master/modules/pre-commit.nix), but that's quite an experimental project anyway.

Let's focus on the problem here, which is probably the initialization of `tools`.

**Comment by lovesegfault** [comment]
@Myhlamaeus any chance you can rebase your PR?

**Comment by domenkozar** [comment]
I've closed that PR as it was out of date and not the approach I'd like to see merged - flake.nix shouldn't duplicate code from non-flake bits.

I'm going to start working towards flake support, starting with cleanups like https://github.com/cachix/pre-commit-hooks.nix/pull/100

**Comment by domenkozar** [comment]
Bumping packages with more cleanup at https://github.com/cachix/pre-commit-hooks.nix/pull/102

**Comment by domenkozar** [comment]
Barebone flake support at https://github.com/cachix/pre-commit-hooks.nix/pull/103, but it's blocked on two issues.

I'd appreciate if a macOS user can help with https://github.com/cachix/pre-commit-hooks.nix/pull/102

**Comment by domenkozar** [comment]
https://github.com/cachix/pre-commit-hooks.nix/pull/103 is ready to be merged, I'd like someone that uses flakes to give it a try!

**Comment by dhess** [comment]
I'm trying it out here:

https://github.com/hackworthltd/haskell-template/tree/pre-commit-hooks-flake

I'm probably being dense, but it's not clear to me out to use `lib.run`. This is what I've got, based on how we used to use it pre-flake:

https://github.com/hackworthltd/haskell-template/blob/4b66ab93e4ef4961e7ffff3298bfe8b6422fcf8e/flake.nix#L76

but I'm getting this error:

```
 nix-build -A hydraJobs.source-code-checks                                                                      /Volumes/src/dhess/haskell-template
error: attempt to call something which is not a function but a set

       at /nix/store/lrj3qxbgdpmdnlc2a9fh732vajdmqynb-source/flake.nix:76:9:

           75|         in
           76|         pre-commit-hooks-nix.lib.${system}.run {
             |         ^
           77|           src = ./.;
(use '--show-trace' to show detailed location information)
```

**Comment by domenkozar** [comment]
Oh, skip `system` on the `lib` output.

**Comment by dhess** [comment]
I tried that as well, but no:

```
 nix build .#hydraJobs.source-code-checks                                                                       /Volumes/src/dhess/haskell-template
warning: Git tree '/Volumes/src/dhess/haskell-template' is dirty
error: attribute 'run' missing

       at /nix/store/n1myzg0ssh4v6vc3xh475cv5hd93qcjc-source/flake.nix:76:9:

           75|         in
           76|         pre-commit-hooks-nix.lib.run {
             |         ^
           77|           src = ./.;
(use '--show-trace' to show detailed location information)
```

**Comment by domenkozar** [comment]
`run` wasn't exported. I've added a test for that. You can try with `pre-commit-hooks-nix.lib.${system}.run` now, I've made the system explicit.

**Comment by dhess** [comment]
Yes, this now works, thanks so much!

**Comment by domenkozar** [comment]
Merged, thanks!

**Comment by domenkozar** [comment]
Docs: https://github.com/cachix/pre-commit-hooks.nix#nix-flakes-support
