### ISSUE TITLE
diverging pre-commit versions

### ISSUE THREAD

**Issue by blaggacao** [cachix/pre-commit-hooks.nix#59]
https://github.com/cachix/pre-commit-hooks.nix/blob/a3f7609ba73eb9ce3fe434d4339101017a430912/nix/packages.nix#L8

It looks to me as if this attribute would not represent the `cfg.package` package version &mdash; if specified.

**Comment by roberth** [comment]
The documented interface (`run`) does not allow overriding the pre-commit package, so realistically I don't expect this to be a problem now.
If anyone decides to use the modules directly for example, they can override the `pre-commit.package` option, in which case they don't import this file.

It does touch #55, about being able to provide your own packages.

**Comment by blaggacao** [comment]
Hm, after (quite) a while I was able to figure this out as well. Since you seem about to refactor some thing arounf those aspects, I'm closing this for now. Thanks for your initiative!
