### ISSUE TITLE
Think of ways to support devshell cli natively

### ISSUE THREAD

**Issue by blaggacao** [cachix/pre-commit-hooks.nix#68]
https://github.com/numtide/devshell/pull/13

`devshell enter` is a go cli tool that bring nix dev shell to the masses. pre-commit is already widely adopted by those target masses.

There should be a way how devshell and pre-commit-hooks.nix can become best friends.

/cc @zimbatm

**Comment by blaggacao** [comment]
Desisting in favour of https://github.com/numtide/devshell/issues/16 as better coordinated improvement over status quo.

**Comment by domenkozar** [comment]
we have it now on https://devenv.sh/pre-commit-hooks/ so this can be mimicked in any other Nix tool
