### ISSUE TITLE
Implementing an ad-hoc pre-commit hook

### ISSUE THREAD

**Issue by chiroptical** [cachix/pre-commit-hooks.nix#86]
The way I was thinking about this previously was my naive understanding of nix. I ended up forking the repository and adding my custom hook but I am still curious if one can implement an ad-hoc pre-commit hook without forking the entire repo.

**edit**: Ignore anything below this line

I see https://github.com/cachix/pre-commit-hooks.nix#contributing-hooks in the documentation but I think it would be helpful to also document how to create ad-hoc pre-commit hooks.

Here is my attempt at adding a custom hook: https://github.com/chiroptical/declarative-programming-streams/blob/64dec6e89fbed46a66d08f638d38a5f8d83da942/default.nix#L1-L25, the error:

```sh
$ nix-build
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels/nixpkgs' does not exist, ignoring
warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
error: The option `hooks.build-readme.entry' is used but not defined.
(use '--show-trace' to show detailed location information)~~
```

I don't know where to go from here and was hoping someone could give me a little guidance. I would be happy to write the section in the README afterwards on custom hooks.

**Comment by u-quark** [comment]
Sorry about the spam here.
