### ISSUE TITLE
Hpack does not seem to be able to deal with package.yaml files in subdirectories

### ISSUE THREAD

**Issue by NorfairKing** [cachix/pre-commit-hooks.nix#93]
```
hpack....................................................................Failed
- hook id: hpack
- exit code: 1

./package.yaml: Yaml file not found: /home/syd/src/sydtest/package.yaml
```

**Comment by domenkozar** [comment]
See https://github.com/cachix/pre-commit-hooks.nix/pull/45 /cc @fiadliel

**Comment by fiadliel** [comment]
The easiest thing would be a `pass_directories` option in pre-commit, but this doesn't exist: https://github.com/pre-commit/pre-commit/issues/1784

The next best thing is a wrapper around `hpack` that takes a list of files from `pass_filenames`, deduplicates them by directory, and runs `hpack` for each directory.

@domenkozar WDYT?

**Comment by fiadliel** [comment]
Also cursed question: does turning filenames into directories have to deal with Windows? :grin:

**Comment by NorfairKing** [comment]
@fiadliel I don't think nix works on windows so don't worry about windows :D

**Comment by domenkozar** [comment]
@fiadliel we have wrappers for some other hooks as well, so LGTM.

**Comment by NorfairKing** [comment]
@fiadliel any news on this?

**Comment by NorfairKing** [comment]
@fiadliel  @domenkozar gentle ping

**Comment by domenkozar** [comment]
I'm not using hpack, but I'm happy to merge a PR if you find a good way forward :)
